name: Generate Newsletter Links

on:
  schedule:
    - cron: '0 0 4 * *'  # Runs at midnight (UTC) on the 4st day of every month
    # Runs at 8:00 AM UTC on the first Monday of every 2nd month
    #- cron: "0 8 * 1,3,5,7,9,11 1"

jobs:
  run-script-and-create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the newsletter script
        env:
            GITHUB_API_KEY: "${{ secrets.GITHUB_TOKEN }}"
            GITHUB_RUN_ID: "${{ github.run_id }}"
        run: python scripts/newsletter.py nfdi4bioimage/training

      - name: Read generated links
        id: get-links
        run: |
          if [ -f scripts/newsletters/newsletter_links.txt ]; then
            content=$(cat scripts/newsletters/newsletter_links.txt)
            echo "::set-output name=links::$content"
          else
            echo "Error: scripts/newsletters/newsletter_links.txt not found."
            exit 1
          fi

      # Step 6: Create GitHub Issue
      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Newsletter Links"
          content-filepath: scripts/newsletters/newsletter_links.txt


