name: deploy-search-site

# Only run this when the master branch changes
on:
  push:
    branches:
    - master
    - main

# This job installs dependencies, builds the search site, and pushes it to `gh-pages`
jobs:
  deploy-search-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        #sudo apt-get install -y poppler-utils

    - name: Build search site
      run: |
        python scripts/build_search_site.py

    # Push the site's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
